# Generated by Django 3.2.5 on 2022-07-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=25, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_rate',
            field=models.CharField(max_length=128, verbose_name='profit_rate'),
        ),
    ]
