# Generated by Django 3.2.5 on 2022-07-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0002_auto_20220711_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateField(blank=True, null=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='product_link'),
        ),
    ]
