# Generated by Django 3.2.5 on 2022-07-12 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0008_alter_product_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateField(default=datetime.datetime, null=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.CharField(blank=True, max_length=25, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime, null=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=25, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=128, verbose_name='product_link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime, null=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_superuser'),
        ),
    ]
