# Generated by Django 3.2.5 on 2022-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0009_auto_20220712_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_volume',
            field=models.CharField(blank=True, max_length=25, verbose_name='sales_volume'),
        ),
    ]
