# Generated by Django 3.2.5 on 2022-07-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0010_product_sales_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_volume',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='sales_volume'),
        ),
    ]
