# Generated by Django 3.2.5 on 2022-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0012_auto_20220713_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='product_link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_rate',
            field=models.CharField(max_length=128, null=True, verbose_name='profit_rate'),
        ),
    ]
