# Generated by Django 3.2.5 on 2022-07-16 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0013_auto_20220715_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit_rate',
            field=models.FloatField(max_length=128, null=True, verbose_name='profit_rate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='password'),
        ),
    ]
